// @vitest-environment node
//
// The aid is generated by CODE (design D2b) at the moment the agent writes a shared collection's
// schema — not invented by the model, and not deferred to the first deploy.
//
// Before this, the two steps disagreed: the agent wrote `app.json` and then created the app's
// first collection, and the acceptance gate refused it with "app.json declares no `aid` string".
// The only ways forward were to invent an aid (the thing the design generates it to prevent) or to
// deploy an app with no collections first, which nobody would think of.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { declaresSharedStorage, refusedForMissingAid, withGeneratedAid } from "../../../server/infra/collectionToolAid.js";
import { makeTempDir } from "../../support/tempDir";

const firestoreSchema = { title: "Bookings", primaryKey: "id", storage: { type: "firestore" }, fields: {} };
const localSchema = { title: "Notes", primaryKey: "id", dataPath: "data/notes/items", fields: {} };

let root = "";
const appJson = () => path.join(root, "app.json");
const aidOf = () => JSON.parse(readFileSync(appJson(), "utf-8")).aid;

/** The engine's refusal when the only thing missing is the aid — its own words, because that is
 *  what this wrapper reads. */
const NO_AID = "/tmp/x/app.json declares no `aid` string";

/** A handler that records what reached it and answers differently on each call, so "was it
 *  retried, and with what?" is answerable. */
const spyHandler = (...answers: string[]) => {
  const calls: Record<string, unknown>[] = [];
  const handler = (args: Record<string, unknown>) => {
    calls.push(args);
    return Promise.resolve(answers[calls.length - 1] ?? answers[answers.length - 1] ?? "inner ran");
  };
  return { calls, handler };
};

describe("declaresSharedStorage", () => {
  it("is true only for a putSchema whose records live in the app", () => {
    expect(declaresSharedStorage({ action: "putSchema", schema: firestoreSchema })).toBe(true);
    expect(declaresSharedStorage({ action: "putSchema", schema: localSchema })).toBe(false);
    // A local collection's repository has no app.json to write to, and giving one to a folder that
    // happens to hold a stray file is a decision this tool has no business making.
    expect(declaresSharedStorage({ action: "getItems", schema: firestoreSchema })).toBe(false);
    expect(declaresSharedStorage({ action: "putSchema" })).toBe(false);
  });
});

describe("refusedForMissingAid", () => {
  it("recognises the engine's refusal and nothing near it", () => {
    expect(refusedForMissingAid(NO_AID)).toBe(true);
    // Two independent markers on purpose: a message about some other part of app.json must not
    // trigger a write.
    expect(refusedForMissingAid("/tmp/x/app.json is not valid JSON")).toBe(false);
    expect(refusedForMissingAid("this schema declares no `aid` field")).toBe(false);
    expect(refusedForMissingAid('{"written":true}')).toBe(false);
  });
});

describe("withGeneratedAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-tool-aid-");
  });

  it("mints the aid on the engine's refusal and runs the write again", async () => {
    writeFileSync(appJson(), JSON.stringify({ members: { "owner@example.com": { "*": "owner" } } }));
    const spy = spyHandler(NO_AID, '{"written":true}');
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toBe('{"written":true}');
    expect(aidOf()).toMatch(/^[0-9a-f]{8}-/);
    // The agent sees the result it would have got if the aid had been there — one call, one answer.
    expect(spy.calls).toHaveLength(2);
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).members).toEqual({ "owner@example.com": { "*": "owner" } });
  });

  it("leaves app.json alone when the engine refused for any OTHER reason", async () => {
    // The whole reason this runs after the engine rather than before it: a refused call must
    // leave nothing behind, and only the engine knows whether the rest of the request was sound.
    writeFileSync(appJson(), JSON.stringify({ members: {} }));
    const spy = spyHandler("unknown collection 'bookings' — create it by writing SKILL.md + schema.json");
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toContain("unknown collection");
    expect(spy.calls).toHaveLength(1);
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).aid).toBeUndefined();
  });

  it("does not run twice when the write succeeded the first time", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", members: {} }));
    const spy = spyHandler('{"written":true}');
    await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(spy.calls).toHaveLength(1);
    expect(aidOf()).toBe("already-there");
  });

  it("says what to write when the folder is not a shared app at all", async () => {
    const spy = spyHandler(NO_AID);
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toContain("app.json");
    expect(message).toContain("members");
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });

  it("does not touch a local collection's write", async () => {
    const spy = spyHandler(NO_AID);
    await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: localSchema });
    expect(spy.calls).toHaveLength(1);
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });
});
