// @vitest-environment node
//
// The aid is generated by CODE (design D2b) at the moment the agent writes a shared collection's
// schema — not invented by the model, and not deferred to the first deploy.
//
// Before this, the two steps disagreed: the agent wrote `app.json` and then created the app's
// first collection, and the acceptance gate refused it with "app.json declares no `aid` string".
// The only ways forward were to invent an aid (the thing the design generates it to prevent) or to
// deploy an app with no collections first, which nobody would think of.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { declaresSharedStorage, withGeneratedAid } from "../../../server/infra/collectionToolAid.js";
import { makeTempDir } from "../../support/tempDir";

const firestoreSchema = { title: "Bookings", primaryKey: "id", storage: { type: "firestore" }, fields: {} };
const localSchema = { title: "Notes", primaryKey: "id", dataPath: "data/notes/items", fields: {} };

let root = "";
const appJson = () => path.join(root, "app.json");
const aidOf = () => JSON.parse(readFileSync(appJson(), "utf-8")).aid;

/** A handler that records what reached it, so "was the inner tool called at all?" is answerable. */
const spyHandler = () => {
  const calls: Record<string, unknown>[] = [];
  const handler = (args: Record<string, unknown>) => {
    calls.push(args);
    return Promise.resolve("inner ran");
  };
  return { calls, handler };
};

describe("declaresSharedStorage", () => {
  it("is true only for a putSchema whose records live in the app", () => {
    expect(declaresSharedStorage({ action: "putSchema", schema: firestoreSchema })).toBe(true);
    expect(declaresSharedStorage({ action: "putSchema", schema: localSchema })).toBe(false);
    // A local collection's repository has no app.json to write to, and giving one to a folder that
    // happens to hold a stray file is a decision this tool has no business making.
    expect(declaresSharedStorage({ action: "getItems", schema: firestoreSchema })).toBe(false);
    expect(declaresSharedStorage({ action: "putSchema" })).toBe(false);
  });
});

describe("withGeneratedAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-tool-aid-");
  });

  it("fills in the aid before the schema is judged against it", async () => {
    writeFileSync(appJson(), JSON.stringify({ members: { "owner@example.com": { "*": "owner" } } }));
    const spy = spyHandler();
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toBe("inner ran");
    expect(aidOf()).toMatch(/^[0-9a-f]{8}-/);
    // The declaration keeps everything the agent wrote.
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).members).toEqual({ "owner@example.com": { "*": "owner" } });
  });

  it("leaves an aid that already exists alone", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", members: {} }));
    await withGeneratedAid(spyHandler().handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(aidOf()).toBe("already-there");
  });

  it("says what to write when the folder is not a shared app at all", async () => {
    const spy = spyHandler();
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    // Refused BEFORE the engine, so the agent gets the actionable reason rather than
    // "declares no `aid` string" about a file that does not exist.
    expect(spy.calls).toHaveLength(0);
    expect(message).toContain("app.json");
    expect(message).toContain("members");
  });

  it("does not touch a local collection's write", async () => {
    const spy = spyHandler();
    await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: localSchema });
    expect(spy.calls).toHaveLength(1);
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });
});
