// Give `app.json` its `aid` BEFORE the agent's schema is judged against it.
//
// The design (D2b) says the aid is generated by code when `app.json` is written — not invented by
// the model, and not deferred to publish. `ensureAid` does the generating, but until now it ran
// only inside `manageSharedApp`, which is a later step than the one that needs it: the acceptance
// gate refuses a firestore schema whose root declares no aid, so an agent writing `app.json` and
// then creating the app's first collection was told
//
//     …/app.json declares no `aid` string
//
// and had no way forward except to invent one — the exact thing the design generates it to
// prevent — or to deploy an app with no collections first, which is not a step anybody would
// think of.
//
// So the aid is filled in HERE, at the moment the schema arrives, and the failure the agent sees
// is the honest one: `app.json` is missing entirely, which means this folder is not a shared app.
//
// Only for a schema that ASKS to be shared. A local collection's repository has no `app.json` to
// write to, and giving one to a folder that happens to have a stray file would be a decision this
// tool has no business making.
import { isRecord } from "../../common/isRecord.js";
import { ensureAid } from "../backends/sharedApp/ensureAid.js";

/** Does this payload write a schema whose records live in the app's Firestore? */
export function declaresSharedStorage(args: Record<string, unknown>): boolean {
  if (args.action !== "putSchema" || !isRecord(args.schema)) return false;
  const storage = args.schema.storage;
  return isRecord(storage) && storage.type === "firestore";
}

/** Wrap a manageCollection handler so a shared collection's `app.json` has an `aid` before the
 *  engine reads it.
 *
 *  A failure is returned as the tool's own prose rather than thrown: the agent's contract with
 *  this tool is text it can act on, and "there is no app.json here" is the most actionable thing
 *  this step can say. */
export function withGeneratedAid(handler: (args: Record<string, unknown>) => Promise<string>, rootOf: () => string) {
  return async (args: Record<string, unknown>): Promise<string> => {
    if (!declaresSharedStorage(args)) return handler(args);
    const ensured = await ensureAid(rootOf());
    if (!ensured.ok) {
      return [
        'This collection declares `storage.type: "firestore"`, which makes it a SHARED collection — its records live in an app\'s Firestore rather than in this repository.',
        "An app is a repository with an `app.json` at its root, and this step could not read one:",
        ...ensured.problems,
        'Write `app.json` first — `{ "members": { "<your address>": { "*": "owner" } } }` is enough, and the `aid` is generated here rather than chosen.',
      ].join("\n");
    }
    return handler(args);
  };
}
