// Give `app.json` its `aid` when the engine says that is the ONE thing missing.
//
// The design (D2b) says the aid is generated by code when `app.json` is written — not invented by
// the model, and not deferred to publish. `ensureAid` does the generating, but it ran only inside
// `manageSharedApp`, which is a later step than the one that needs it: the acceptance gate refuses
// a firestore schema whose root declares no aid, so an agent writing `app.json` and then creating
// the app's first collection was told
//
//     …/app.json declares no `aid` string
//
// and had no way forward except to invent one — the exact thing the design generates it to
// prevent — or to deploy an app with no collections first, which is not a step anybody would
// think of.
//
// WHY AFTERWARDS, AND NOT BEFORE. Minting on the way in would write a UUID into `app.json` for a
// call the engine then rejects for some other reason — an unknown slug, a schema that does not
// parse — and a refused tool call must leave nothing behind. Running the write first and reading
// its refusal inverts that: the engine reaches its aid gate only once everything else about the
// request is in order, so the refusal itself is the evidence that minting is warranted. Then the
// call is retried, and the agent sees the result it would have got if the aid had been there.
import { isRecord } from "../../common/isRecord.js";
import { ensureAid } from "../backends/sharedApp/ensureAid.js";

/** Does this payload write a schema whose records live in the app's Firestore?
 *
 *  Only those. A local collection's repository has no `app.json` to write to, and giving one to a
 *  folder that happens to hold a stray file is a decision this tool has no business making. */
export function declaresSharedStorage(args: Record<string, unknown>): boolean {
  if (args.action !== "putSchema" || !isRecord(args.schema)) return false;
  const storage = args.schema.storage;
  return isRecord(storage) && storage.type === "firestore";
}

/** Is this refusal the missing aid, and nothing else?
 *
 *  Matched on the engine's own words because the tool answers in prose — there is no code to read.
 *  Narrow on purpose: two independent markers, so a message about some other part of `app.json`
 *  does not trigger a write. Missing the match costs nothing worse than today's behaviour, which
 *  is the refusal reaching the agent unchanged. */
export function refusedForMissingAid(narration: string): boolean {
  return narration.includes("app.json") && narration.includes("declares no `aid`");
}

/** Wrap a manageCollection handler so a shared collection's first write mints the app's aid.
 *
 *  A failure is returned as prose rather than thrown: the agent's contract with this tool is text
 *  it can act on, and "there is no app.json here" is the most actionable thing this step can say. */
export function withGeneratedAid(handler: (args: Record<string, unknown>) => Promise<string>, rootOf: () => string) {
  return async (args: Record<string, unknown>): Promise<string> => {
    const narration = await handler(args);
    if (!declaresSharedStorage(args) || !refusedForMissingAid(narration)) return narration;
    const ensured = await ensureAid(rootOf());
    if (!ensured.ok) return noAppJson(ensured.problems);
    // The same call again, now that the one thing it was missing is there.
    return handler(args);
  };
}

function noAppJson(problems: readonly string[]): string {
  return [
    'This collection declares `storage.type: "firestore"`, which makes it a SHARED collection — its records live in an app\'s Firestore rather than in this repository.',
    "An app is a repository with an `app.json` at its root, and this step could not read one:",
    ...problems,
    'Write `app.json` first — `{ "members": { "<your address>": { "*": "owner" } } }` is enough, and the `aid` is generated here rather than chosen.',
  ].join("\n");
}
