// @vitest-environment node
//
// The `aid` is generated by CODE, not by the agent (design D2b) — so what this pins is that the
// generator behaves like one: it mints exactly once, it keeps what the author wrote, and it
// refuses rather than inventing a declaration.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ensureAid } from "../../../server/backends/sharedApp/ensureAid.js";
import { makeTempDir } from "../../support/tempDir";

let root = "";
const appJson = (): string => path.join(root, "app.json");
const read = (): Record<string, unknown> => JSON.parse(readFileSync(appJson(), "utf-8"));

describe("ensureAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-ensure-aid-");
  });

  it("mints a uuid when app.json has none, and keeps everything else the author wrote", () => {
    writeFileSync(appJson(), JSON.stringify({ name: "Sakura", members: { "owner@example.com": { "*": "owner" } } }));
    return ensureAid(root).then((result) => {
      expect(result.ok && result.created).toBe(true);
      // A UUID, not a memorable name: `apps/{aid}` is a shelf every user shares and a memorable
      // id is first-come-first-served (D2b).
      expect(result.ok && result.aid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
      const written = read();
      expect(written.aid).toBe(result.ok && result.aid);
      expect(written.name).toBe("Sakura");
      expect(written.members).toEqual({ "owner@example.com": { "*": "owner" } });
    });
  });

  it("keeps the aid it already has — the id is the app's identity, not a per-run value", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", name: "Sakura" }, null, 2));
    const first = await ensureAid(root);
    expect(first.ok && first.aid).toBe("already-there");
    expect(first.ok && first.created).toBe(false);
    // Twice, because "mints every time" and "mints once" look identical on a single call.
    const second = await ensureAid(root);
    expect(second.ok && second.aid).toBe("already-there");
  });

  it("refuses a missing app.json rather than writing one", async () => {
    const result = await ensureAid(root);
    expect(result.ok).toBe(false);
    // Writing a bare `{ aid }` would turn a mistyped path into an app declaration.
    expect(result.ok === false && result.problems.join(" ")).toContain("app.json");
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });

  it("refuses a broken app.json rather than replacing it", async () => {
    writeFileSync(appJson(), "{ not json");
    const result = await ensureAid(root);
    expect(result.ok).toBe(false);
    expect(readFileSync(appJson(), "utf-8")).toBe("{ not json");
  });

  it("refuses a JSON file that is not an object", async () => {
    writeFileSync(appJson(), "[]");
    expect((await ensureAid(root)).ok).toBe(false);
  });
});
